### ISSUE TITLE
document.ready not compiling

### ISSUE THREAD

**Issue by ghost** [ZiggyV/gulp-sass-boilerplate#1]
With your boilerplate, following script is working under gulp-dev but once I make a build using gulp, the final site does not execute the script.

`
(function ($) {

        
    $(document).ready(function () {
        $('#pagepiling').pagepiling();

    });
})(jQuery);
`

There is no error in console. Script simply not running at all.

**Comment by ZiggyV** [comment]
There is no error in your console because the script is executing just fine. 

The problem here is that [pagePiling.js](https://github.com/alvarotrigo/pagePiling.js) adds a lot of CSS selectors via JavaScript and when you use the `gulp` command to build your project all of these selectors get removed by the [gulp-purgecss](https://github.com/FullHuman/gulp-purgecss) plugin since it can't find those in the raw HTML file. But you can whitelist selectors and even patterns. 

To help you out I've added a whitelistPatterns example in the following commit: https://github.com/ZiggyV/gulp-sass-boilerplate/commit/7c63b5b4e0cb22ee40ff03867a5ebfec7017c6bf.

This will ensure that the `gulp-purgecss` task won't remove any of the pagePiling.js CSS.
